#!/bin/bash
#
# Obtained from VPP - https://wiki.fd.io/view/VPP
#

path=$( cd "$(dirname "${BASH_SOURCE}")" ; pwd -P )

cd "$path"

if [ -f .version ]; then
    vstring=$(cat .version)
else
    vstring=$(git describe --match '[vR]*')
    if [ $? != 0 ]; then
      exit 1
    fi
fi

TAG=$(echo ${vstring} | cut -d- -f1 | sed -e 's/^[vR]//')
ADD=$(echo ${vstring} | cut -s -d- -f2)

if [ ! -f .version ] && git rev-parse 2>/dev/null; then
    CMT=$(git describe --dirty --match '[vR]*'| cut -s -d- -f3,4)
else
    CMT=$(echo ${vstring} | cut -s -d- -f3,4)
fi
CMTR=$(echo $CMT | sed 's/-/_/')

if [ -n "${BUILD_NUMBER}" ]; then
       BLD="~b${BUILD_NUMBER}"
fi

if [ "$1" = "rpm-version" ]; then
  echo -n ${TAG}
  exit
fi

if [ "$1" = "rpm-release" ]; then
  [ -z "${ADD}" ] && echo -n release && exit
  echo -n ${ADD}${CMTR:+~${CMTR}}${BLD}
  exit
fi

  if [ -n "${ADD}" ]; then
    if [ "$1" = "rpm-string" ]; then
      echo -n ${TAG}-${ADD}${CMTR:+~${CMTR}}${BLD}
    else
      echo -n ${TAG}-${ADD}${CMT:+~${CMT}}${BLD}
    fi
  else
    echo -n ${TAG}-1
fi
