#!/bin/bash
#
# Obtained from VPP - https://wiki.fd.io/view/VPP
#
# ex: tabstop=4 shiftwidth=4 softtabstop=4 expandtab

path=$( cd "$(dirname "${BASH_SOURCE}")" ; pwd -P )

cd "$path"

if [ -f .version ]; then
    vstring=$(cat .version)
    TAG=$(echo ${vstring} | cut -d- -f1)
    ADD=$(echo ${vstring} | sed 's/^[^-]*-//')
else
    vstring=$(git describe --match 'frr-*')
    if [ $? != 0 ]; then
        exit 1
    fi
    vstring=$(echo "${vstring}" | sed 's/^frr-//')

    TAG=$(echo ${vstring} | cut -d- -f1)
    ADD=$(echo ${vstring} | cut -s -d- -f2)

    git rev-parse 2> /dev/null
    if [ $? -eq 0 ]; then
        CMT=$(git describe --match 'frr-*' --dirty | cut -s -d- -f4,5)
    else
        CMT=$(echo ${vstring} | cut -s -d- -f3,4)
    fi

    if [ -n "${BUILD_NUMBER}" ]; then
        BLD="b${BUILD_NUMBER}"
    elif [ -n "${BUILD_VER_TIMESTAMP}" ]; then
        BLD="d${BUILD_VER_TIMESTAMP}"
    fi
fi

test -z "${ADD}" && ADD=1

SUFFIX="${CMT:++}${CMT}"
if [ -z "${SUFFIX}" ]; then
    SUFFIX="${BLD:++}${BLD}"
else
    SUFFIX="${SUFFIX}${BLD:+-}${BLD}"
fi

echo ${TAG}-${ADD}${SUFFIX}
